DELETE http://localhost:3001/api/blogs/68e2a8696b6906d8158e98fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNyZWF0b3JQb3dlciIsImlkIjoiNjhlMjk3YzdiMzU2MWRkY2JkNjhhYjlmIiwiaWF0IjoxNzU5NzU2NDQzLCJleHAiOjE3NTk3NjAwNDN9.aFLozFj3ICzVFOIANxrrc-lUm68DBTmbO2VmT6xxK9Q