POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNyaXMiLCJpZCI6IjY4ZTEzZWI2ZWVjOWMzZWQ4ZWYzMWNmYiIsImlhdCI6MTc1OTY3OTY4Mn0.HtihHb8gcIrJ4ELzsp99iStg3qxKxJh290XeXkG9vYk

{
  "author": "some author",
  "title": "some new user title",
  "url": "some new user url",
  "likes": 22
}