DELETE http://localhost:3001/api/blogs/68e14397ec0d7ff27fc194ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNyZWF0b3JQb3dlciIsImlkIjoiNjhlMjk3YzdiMzU2MWRkY2JkNjhhYjlmIiwiaWF0IjoxNzU5Njg4MjM1LCJleHAiOjE3NTk2OTE4MzV9.1xNqCWbX53izsaGwJDgWxHLEtGQeghUQyOothLLKpoA